<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "gswarranty"
 *
 * Auto generated by Extension Builder 2017-03-13
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'GS Warranty',
    'description' => 'GS Warranty is for internal use only!',
    'category' => 'be',
    'author' => 'Simon Gilli',
    'author_email' => 'typo3@gilbertsoft.org',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '7.6.2',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.9.99',
            'backend' => '7.6.0-8.9.99',
            't3skin' => '7.6.0-8.9.99',
        ],
        'conflicts' => [],
        'suggests' => [
            'bootstrap_package' => '7.0.0-0.0.0',
        ],
    ],
];
